- name: Community Scan Tool
  introduce: 安全扫描工具社区版
- name: Community Talent Certification
  introduce: openEuler社区人才认证IT系统
- name: Contributor License Agreement
  introduce: 开源社区SLA签署
- name: Etherpad
  introduce: 记事本
- name: Explainshell
  introduce: Shell命令解释服务
- name: Infra Scan Tools
  introduce: 安全扫描工具基础设施专用版
- name: Kunpenghui Jenkins
  introduce: 鲲鹏Jenkins
- name: MAJUN
  introduce: 代码门禁
- name: Metadata Service
  introduce: 代码仓元数据下载
- name: MindSpore Binaries
  introduce: MindSpore包管理
- name: MindSpore Datastat
  introduce: MindSpore社区数据展示
- name: MindSpore Download
  introduce: MindSpore资源下载
- name: MindSpore Jenkins
  introduce: MindSpore社区Jenkins
- name: MindSpore Mailweb
  introduce: MindSpore社区邮箱列表
- name: MindSpore Meetings
  introduce: MindSpore会议小程序
- name: MindSpore paste
  introduce: 上传代码生成分享链接
- name: MindSpore SMTP
  introduce: MindSpore社区邮件发送服务
- name: MindSpore Sunmao
  introduce: MindSpore社区标签机器人服务
- name: MindSpore Website
  introduce: MindSpore官网
- name: MindSpore WWW
  introduce: MindSpore官网
- name: openEuler Beijing Mirror
  introduce: openEuler镜像北京下载地址
- name: openEuler Bugzilla
  introduce: 漏洞搜索服务
- name: openEuler Community Certificate
  introduce: openEuler社区认证服务
- name: openEuler Compass CI Platform
  introduce: 开发式测试服务平台Compass CI首页
- name: openEuler CVE Manager
  introduce: openEuler社区CVE管理状态展示
- name: openEuler Datastat
  introduce: openEuler社区数据展示
- name: openEuler Document
  introduce: openEuler社区文档
- name: openEuler Etherpad
  introduce: 记事本
- name: openEuler HongKong
  introduce: openEuler官网
- name: openEuler HongKong Mirror
  introduce: openEuler镜像下载网站
- name: openEuler Jenkins CI
  introduce: openEuler镜像构建Jenkins服务
- name: openEuler License Show Room
  introduce: 貂蝉License展示
- name: openEuler Mailling List
  introduce: openEuler社区邮箱列表
- name: openEuler Meetings
  introduce: openEuler社区会议小程序
- name: openEuler MirrorManager
  introduce: openEuler官网
- name: openEuler Moscow
  introduce: openEuler俄语官网
- name: openEuler Moscow Mirror
  introduce: openEuler俄罗斯镜像下载网站
- name: openEuler OmniBuildPlatform
  introduce: openEuler社区镜像构建下载服务
- name: openEuler Package Build
  introduce: openEuler社区OBS
- name: openEuler Package Manage
  introduce: openEuler Package Management
- name: openEuler paste
  introduce: 上传代码生成分享链接
- name: openEuler PlayGround
  introduce: openEuler学习平台
- name: openEuler PlayGround2
  introduce: openEuler学习平台
- name: openEuler SMTP
  introduce: openEuler社区邮件发送服务
- name: openEuler-ECS-Prometheus
  introduce: prometheus监控服务
- name: openGauss Blog
  introduce: openGauss博客
- name: openGauss Datastat
  introduce: openGauss社区数据展示
- name: openGauss Etherpad
  introduce: 记事本
- name: openGauss HongKong Website
  introduce: openGauss官网
- name: openGauss Jenkins
  introduce: openGauss社区jenkins服务
- name: openGauss Mailweb
  introduce: openGauss社区邮箱
- name: openGauss Meetings
  introduce: openGauss社区会议小程序
- name: openGauss Moocstudio
  introduce: openGauss社区学习平台
- name: openGauss odd
  introduce: openGauss社区开发者大会人传人海报生成服务
- name: openGauss paste
  introduce: 上传代码生成分享链接
- name: openGauss SMTP
  introduce: openGauss社区邮件发送服务
- name: openLooKeng Datastat
  introduce: openLooKeng社区数据展示
- name: openLooKeng docs
  introduce: openLooKeng社区文档服务
- name: openLooKeng docs-bug
  introduce: openLooKeng社区文档捉虫服务
- name: openLooKeng Download
  introduce: openLooKeng社区资源下载服务
- name: openLooKeng Jenkins
  introduce: openLooKeng社区Jenkins服务
- name: openLooKeng Mailweb
  introduce: openLooKeng社区邮件列表
- name: openLooKeng paste
  introduce: 上传代码生成分享链接
- name: openLooKeng SMTP
  introduce: openLooKeng社区邮件发送服务
- name: openLooKeng Tryme
  introduce: openLooKeng集群部署介绍网站
- name: openLooKeng Website
  introduce: openLooKeng社区官网
- name: paas robot
  introduce: Kurator项目prow机器人
- name: Ptadapter Jenkins
  introduce: 昇腾Jenkins服务
- name: Software Composition Analysis
  introduce: 风险数据看板