- name: Community Scan Tool
  introduce: 安全扫描工具社区版
  name-alias: community-scan-tools
- name: Community Talent Certification
  introduce: openEuler社区人才认证IT系统
  name-alias: community-certification-system
- name: Contributor License Agreement
  introduce: 开源社区SLA签署
  name-alias: infrastructure-cla
- name: Etherpad
  introduce: 记事本
- name: Explainshell
  introduce: Shell命令解释服务
  name-alias: infrastructure-cla
- name: Infra Scan Tools
  introduce: 安全扫描工具基础设施专用版
  name-alias: infra-scan-tools
- name: Kunpenghui Jenkins
  introduce: 鲲鹏Jenkins
- name: MAJUN
  introduce: 代码门禁
- name: Metadata Service
  introduce: 代码仓元数据下载
- name: MindSpore Binaries
  introduce: MindSpore包管理
  name-alias: mindspore-cn-north4-repo
- name: MindSpore Datastat
  introduce: MindSpore社区数据展示
  name-alias: opendesign-datapertus-control
- name: MindSpore Download
  introduce: MindSpore资源下载
  name-alias: mindspore-cn-north4-repo-download-new
- name: MindSpore Jenkins
  introduce: MindSpore社区Jenkins
  name-alias: mindspore-jenkins-master
- name: MindSpore Mailweb
  introduce: MindSpore社区邮箱列表
  name-alias: mindspore-mail
- name: MindSpore Meetings
  introduce: MindSpore会议小程序
  name-alias: mindspore-cn-north4-meetingserver
- name: MindSpore paste
  introduce: 上传代码生成分享链接
  name-alias: control-paste
- name: MindSpore SMTP
  introduce: MindSpore社区邮件发送服务
- name: MindSpore Sunmao
  introduce: MindSpore社区标签机器人服务
- name: MindSpore Website
  introduce: MindSpore官网
  name-alias: mindspore-cn-north4-website
- name: MindSpore WWW
  introduce: MindSpore官网
  name-alias: mindspore-cn-north4-website
- name: openEuler Beijing Mirror
  introduce: openEuler镜像北京下载地址
  name-alias: openeuler-beijing-repo
- name: openEuler Bugzilla
  introduce: 漏洞搜索服务
  name-alias: openeuler-hk-bugzilla
- name: openEuler Community Certificate
  introduce: openEuler社区认证服务
  name-alias: openeuler-ccs
- name: openEuler Compass CI Platform
  introduce: 开发式测试服务平台Compass CI首页
  name-alias: openeuler-hk-compass-ci
- name: openEuler CVE Manager
  introduce: openEuler社区CVE管理状态展示
  name-alias: openeuler-hk-cve-manager
- name: openEuler Datastat
  introduce: openEuler社区数据展示
  name-alias: opendesign-datapertus-control
- name: openEuler Document
  introduce: openEuler社区文档
  name-alias: openeuler-hk-website-docs
- name: openEuler Etherpad
  introduce: 记事本
  name-alias: openeuler-hk-etherpad
- name: openEuler HongKong
  introduce: openEuler官网
  name-alias: openeuler-hk-website-v2
- name: openEuler HongKong Mirror
  introduce: openEuler镜像下载网站
  name-alias: openeuler-hk-repo
- name: openEuler Jenkins CI
  introduce: openEuler镜像构建Jenkins服务
  name-alias: openeuler-cn-north4-jenkins-2
- name: openEuler License Show Room
  introduce: 貂蝉License展示
- name: openEuler Mailling List
  introduce: openEuler社区邮箱列表
  name-alias: openeuler-hk-mail
- name: openEuler Meetings
  introduce: openEuler社区会议小程序
  name-alias: openeuler-hk-meetingserver
- name: openEuler MirrorManager
  introduce: openEuler官网
  name-alias: openeuler-hk-repo-mirrorbits
- name: openEuler Moscow
  introduce: openEuler俄语官网
  name-alias: openeuler-mos-website-ru
- name: openEuler Moscow Mirror
  introduce: openEuler俄罗斯镜像下载网站
  name-alias: openeuler-mos-repo
- name: openEuler OmniBuildPlatform
  introduce: openEuler社区镜像构建下载服务
  name-alias: openeuler-hk-omni-manager-website
- name: openEuler Package Build
  introduce: openEuler社区OBS
- name: openEuler Package Manage
  introduce: openEuler Package Management
  name-alias: openeuler-hk-package-manage
- name: openEuler paste
  introduce: 上传代码生成分享链接
  name-alias: control-paste
- name: openEuler PlayGround
  introduce: openEuler学习平台
  name-alias: moocstudio-openeuler-webiste-frontend
- name: openEuler PlayGround2
  introduce: openEuler学习平台
  name-alias: moocstudio-openeuler-webiste-frontend
- name: openEuler SMTP
  introduce: openEuler社区邮件发送服务
- name: openEuler-ECS-Prometheus
  introduce: prometheus监控服务
  name-alias: control-openeuler-ecs-cn-north4-promethues-ingress
- name: openGauss Blog
  introduce: openGauss博客
  name-alias: opengauss-hk-blog
- name: openGauss Datastat
  introduce: openGauss社区数据展示
  name-alias: opendesign-datapertus-control
- name: openGauss Etherpad
  introduce: 记事本
  name-alias: opengauss-hk-etherpad
- name: openGauss HongKong Website
  introduce: openGauss官网
  name-alias: opengauss-hk-website
- name: openGauss Jenkins
  introduce: openGauss社区jenkins服务
  name-alias: opengauss-hk-jenkins
- name: openGauss Mailweb
  introduce: openGauss社区邮箱
  name-alias: opengauss-mail
- name: openGauss Meetings
  introduce: openGauss社区会议小程序
  name-alias: opengauss-hk-meetingserver
- name: openGauss Moocstudio
  introduce: openGauss社区学习平台
  name-alias: moocstudio-opengauss-website
- name: openGauss odd
  introduce: openGauss社区开发者大会人传人海报生成服务
  name-alias: opengauss-website-odd
- name: openGauss paste
  introduce: 上传代码生成分享链接
  name-alias: control-paste
- name: openGauss SMTP
  introduce: openGauss社区邮件发送服务
- name: openLooKeng Datastat
  introduce: openLooKeng社区数据展示
  name-alias: opendesign-datapertus-control
- name: openLooKeng docs
  introduce: openLooKeng社区文档服务
  name-alias: openlookeng-website-docs
- name: openLooKeng docs-bug
  introduce: openLooKeng社区文档捉虫服务
  name-alias: openlookeng-website-bugs
- name: openLooKeng Download
  introduce: openLooKeng社区资源下载服务
- name: openLooKeng Jenkins
  introduce: openLooKeng社区Jenkins服务
  name-alias: openlookeng-jenkins-ingress
- name: openLooKeng Mailweb
  introduce: openLooKeng社区邮件列表
  name-alias: openlookeng-mail-ingress
- name: openLooKeng paste
  introduce: 上传代码生成分享链接
  name-alias: control-paste
- name: openLooKeng SMTP
  introduce: openLooKeng社区邮件发送服务
- name: openLooKeng Tryme
  introduce: openLooKeng集群部署介绍网站
  name-alias: openlookeng-tryme-ingress
- name: openLooKeng Website
  introduce: openLooKeng社区官网
  name-alias: openlookeng-website-ingress
- name: paas robot
  introduce: Kurator项目prow机器人
- name: Ptadapter Jenkins
  introduce: 昇腾Jenkins服务
- name: Software Composition Analysis
  introduce: 风险数据看板
- name: openEuler France Mirror
  introduce: openEuler巴黎镜像站点
- name: openEuler Reproducible Builds
  introduce: openEuler可重复构建
  name-alias: openeuler-reproducible-production-environment
- name: MindSpore Reproducible Builds
  introduce: MindSpore可重复构建
  name-alias: mindspore-reproducible-production-environment
- name: openGauss Reproducible Builds
  introduce: openGauss可重复构建
  name-alias: opengauss-reproducible-production-environment
- name: voting
  introduce: helios投票服务
  name-alias: helios-server
- name: openEuler QA Robot
  introduce: openEuler社区客服机器人欧拉小智
  name-alias: openeuler-qa-robot-production-environment